name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  token:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)"
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
