name: "Check Other Workflows"
description: "Check other workflows and output the status"
author: "tyankastu0105"

inputs:
  token:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)"
    default: ${{ github.token }}
  interval:
    description: "The interval of checking other workflows"
    default: "5000"

outputs:
  status:
    description: "The status of result after checking other workflows"

runs:
  using: "node18"
  main: "dist/index.js"

branding:
  icon: "check-square"
  color: "green"
