name: label action

on:
  pull_request:
    types: [labeled]

jobs:
  label-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: sleep
        run: sleep 30s
        shell: bash

      - run: exit 1
      # - run: echo "Hello World"
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - run: npm run build

      - uses: ./
        with:
          token: ${{ github.token }}
          interval: 10000
